title: Kimmy's personal site
email: kenpusney#at#gmail.com
author: Kimmy Leo
# Build settings
markdown: kramdown

plugins:
  - jekyll-toc
  - jekyll-seo-tag
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-optional-front-matter
  - jekyll-relative-links
toc:
  max_level: 3